sudo: required

services:
  - docker

before_install:
  - docker build -t monimarr/client -f Dockerfile.dev .
deploy:
  provider: elasticbeanstalk
  region: "us-east-2" #get from the url
  app: "docker-react" #application name
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-778531540051"
  bucket_path: "docker-react" #same as application name
  on:
    branch: master #means whenever pushed code to master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY
script:
  - docker run monimarr/client npm run test -- --coverage

