sudo: required
services: 
  - docker

  before_install: 
    - docker build -t monicamarroyo/Monica_Salon_React -f Dockerfile.dev .
  
  script: 
    - docker run monicamarroyo/Monica_Salon_React npm run test -- --coverage